PAYMENTS_NEW = "payments.new"
PAYMENTS_NEW_DLQ = f"{PAYMENTS_NEW}.dlq"

EVENT_PAYMENTS_NEW = PAYMENTS_NEW
ROUTING_KEY_PAYMENTS_NEW = PAYMENTS_NEW
EXCHANGE_PAYMENTS_EVENTS = "payments.events"
DLX_EXCHANGE = "payments.dlx"
DLQ_ROUTING_KEY = PAYMENTS_NEW_DLQ
QUEUE_PAYMENTS_NEW = PAYMENTS_NEW
QUEUE_DLQ = PAYMENTS_NEW_DLQ
